### ISSUE TITLE
[BUG] Remove the need of systemd on Linux build

### ISSUE THREAD

**Issue by oxxide216** [travisvroman/kohi#289]
**Is your feature request related to a problem? Please describe.**
I was excited when I found the series on YouTube and wanted to build the engine. However. I was not able to.
It requires systemd headers that I don't have because I use a different init system (runit).

**Describe the solution you'd like**
I would like systemd-dependent code to be removed/put behind a feature flag.

**Describe alternatives you've considered**
I could solve this issue myself if you will say that you will accept it.
I just need to have an understanding of why systemd-related code is even within the engine and what it does. 

**Additional context**
```
src/platform/platform_linux.c...
src/platform/platform_linux.c:51:11: fatal error: 'systemd/sd-bus.h' file not found
   51 | #       include <systemd/sd-bus.h>
      |                 ^~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by travisvroman** [comment]
Thanks for submitting this!

This was admittedly a bad shortcut I took to quickly get OS-level open file dialogs in place on the platform. I should have just used straight-up dbus for this instead (dynamically linked instead of statically at that) - this would eliminate that dependency without the need for a feature flag.

For you at the moment, you can work around it by just commenting out the code that uses it - which for now is only the open file dialog logic. And the only place that is used is in the texture browser to import new textures via the UI.

I'll try to work in a fix for this in the 0.13 release.

**Comment by oxxide216** [comment]
Ok, thank you! And thank you for this series! I work on some game/game engine/Vulkan related project currently and it is interesting to watch your videos in parallel.
